export const RECEIVED_INITIAL_DATA = 'RECEIVED_INITIAL_DATA';

export const APP_PAGE_CHANGE = 'APP_PAGE_CHANGE';
export const APP_WINDOW_RESIZE = 'APP_WINDOW_RESIZE';

export const BOOK_CHANGE_PAGE = 'BOOK_CHANGE_PAGE';
export const BOOK_BEGINNING = 'BOOK_BEGINNING';
export const BOOK_FINISHED = 'BOOK_FINISHED';
export const BOOK_SELECT_BALLOON = 'BOOK_SELECT_BALLOON';
export const BOOK_DESELECT_BALLOONS = 'BOOK_DESELECT_BALLOONS';
export const BOOK_ENDING_PAGE_OPENED = 'BOOK_ENDING_PAGE_OPENED';
export const BOOK_ENDING_PAGE_CLOSED = 'BOOK_ENDING_PAGE_CLOSED';
export const BOOK_ZOOMED_IN = 'BOOK_ZOOMED_IN';
export const BOOK_ZOOMED_OUT = 'BOOK_ZOOMED_OUT';

export const TRANSLATION_BALLOONS_SIDE_CHANGE = 'TRANSLATION_BALLOONS_SIDE_CHANGE';

export const CALL_READ_CHAPTER_BEGIN = 'CALL_READ_CHAPTER_BEGIN';
export const CALL_READ_CHAPTER_SUCCESS = 'CALL_READ_CHAPTER_SUCCESS';
export const CALL_READ_CHAPTER_CANCEL = 'CALL_READ_CHAPTER_CANCEL';
export const CALL_READ_CHAPTER_FAIL = 'CALL_READ_CHAPTER_FAIL';

export const CALL_CREATE_TRANSLATION_BEGIN = 'CALL_CREATE_TRANSLATION_BEGIN';
export const CALL_CREATE_TRANSLATION_SUCCESS = 'CALL_CREATE_TRANSLATION_SUCCESS';
export const CALL_CREATE_TRANSLATION_CANCEL = 'CALL_CREATE_TRANSLATION_CANCEL';
export const CALL_CREATE_TRANSLATION_FAIL = 'CALL_CREATE_TRANSLATION_FAIL';

export const CALL_CREATE_COMMENT_BEGIN = 'CALL_CREATE_COMMENT_BEGIN';
export const CALL_CREATE_COMMENT_SUCCESS = 'CALL_CREATE_COMMENT_SUCCESS';
export const CALL_CREATE_COMMENT_CANCEL = 'CALL_CREATE_COMMENT_CANCEL';
export const CALL_CREATE_COMMENT_FAIL = 'CALL_CREATE_COMMENT_FAIL';

export const CALL_REMOVE_COMMENT_BEGIN = 'CALL_REMOVE_COMMENT_BEGIN';
export const CALL_REMOVE_COMMENT_SUCCESS = 'CALL_REMOVE_COMMENT_SUCCESS';
export const CALL_REMOVE_COMMENT_CANCEL = 'CALL_REMOVE_COMMENT_CANCEL';
export const CALL_REMOVE_COMMENT_FAIL = 'CALL_REMOVE_COMMENT_FAIL';
